# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - waist_joint
      - upperarm_joint
      - lowerarm_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true